"""
Daftar LENGKAP ticker IDX (Bursa Efek Indonesia)
Sumber: Data resmi IDX - https://www.idx.co.id
Total: 962 saham terdaftar
"""

IDX_TICKERS_COMPLETE = [
    'AADI', 'AALI', 'ABBA', 'ABDA', 'ABMM', 'ACES', 'ACRO', 'ACST', 'ADES', 'ADHI',
    'ADMF', 'ADMG', 'ADMR', 'ADRO', 'AEGS', 'AGAR', 'AGII', 'AGRO', 'AGRS', 'AHAP',
    'AIMS', 'AISA', 'AKKU', 'AKPI', 'AKRA', 'AKSI', 'ALDO', 'ALII', 'ALKA', 'ALMI',
    'ALTO', 'AMAG', 'AMAN', 'AMAR', 'AMFG', 'AMIN', 'AMMS', 'AMMN', 'AMOR', 'AMRT',
    'ANJT', 'ANTM', 'APEX', 'APIC', 'APII', 'APLI', 'APLN', 'AREA', 'ARGO', 'ARKA',
    'ARKO', 'ARNA', 'ARTO', 'ARTA', 'ARTI', 'ASBI', 'ASDM', 'ASGR', 'ASII', 'ASJT',
    'ASLC', 'ASLI', 'ASMI', 'ASPI', 'ASRI', 'ASRM', 'ASSA', 'ATIC', 'ATLA', 'ATPK',
    'AUTO', 'AVIA', 'AWAN', 'AYAM', 'AYLS', 'BABP', 'BABY', 'BAIK', 'BAJA', 'BALI',
    'BANK', 'BAPA', 'BAPI', 'BATA', 'BATR', 'BAUT', 'BAYU', 'BBCA', 'BBHI', 'BBKP',
    'BBLD', 'BBMD', 'BBNI', 'BBRI', 'BBRM', 'BBSS', 'BBTN', 'BBYB', 'BCAP', 'BCIC',
    'BCIP', 'BDMN', 'BDMS', 'BEER', 'BELI', 'BELL', 'BESS', 'BEST', 'BFIN', 'BGTG',
    'BHAT', 'BHIT', 'BIKA', 'BIKE', 'BIMA', 'BINA', 'BIPI', 'BIPP', 'BIRD', 'BISI',
    'BJBR', 'BJTM', 'BKDP', 'BKSL', 'BKSW', 'BLES', 'BLTA', 'BLTZ', 'BMAS', 'BMHS',
    'BMRI', 'BMSR', 'BMTR', 'BNBA', 'BNBR', 'BNGA', 'BNII', 'BNLI', 'BOLT', 'BOSS',
    'BOAT', 'BOGA', 'BOLA', 'BPAT', 'BPFI', 'BPII', 'BPRI', 'BPTR', 'BRAM', 'BRIS',
    'BRMS', 'BRNA', 'BRPT', 'BRTI', 'BSBK', 'BSDE', 'BSIM', 'BSML', 'BSSR', 'BSWD',
    'BTEK', 'BTEL', 'BTON', 'BTPN', 'BTPS', 'BUDI', 'BUKK', 'BULL', 'BUMI', 'BUVA',
    'BVIC', 'BWPT', 'BYAN', 'CAMP', 'CANI', 'CARE', 'CARS', 'CASH', 'CASS', 'CBDK',
    'CBMF', 'CBPE', 'CBRE', 'CBUT', 'CEKA', 'CENT', 'CFIN', 'CGAS', 'CHEM', 'CHIP',
    'CINT', 'CITA', 'CLEO', 'CLPI', 'CLAY', 'CMNP', 'CMNT', 'CMPP', 'CMRI', 'CNKO',
    'CNMA', 'CNTX', 'COCO', 'COAL', 'CPIN', 'CPRO', 'CPRI', 'CRAB', 'CRSN', 'CSAP',
    'CSIS', 'CSMI', 'CSRA', 'CUAN', 'DAAZ', 'DADA', 'DART', 'DATA', 'DAYA', 'DEAL',
    'DEPO', 'DEWI', 'DFAM', 'DGIK', 'DGNS', 'DGWG', 'DIGI', 'DKFT', 'DLTA', 'DMAS',
    'DMND', 'DNAR', 'DNET', 'DOID', 'DOOH', 'DOSS', 'DPNS', 'DPUM', 'DRMA', 'DSFI',
    'DSNG', 'DSSA', 'DUCK', 'DUTI', 'DVLA', 'DWGL', 'DYAN', 'EAST', 'ECII', 'EDGE',
    'EKAD', 'ELIT', 'ELPI', 'ELSA', 'ELTY', 'EMDE', 'EMTK', 'ENAK', 'ENRG', 'ENZO',
    'EPAC', 'EPMT', 'ERAA', 'ERAL', 'ERTX', 'ESSA', 'ESTA', 'ESTI', 'ETWA', 'EURO',
    'EXCL', 'FAPA', 'FAST', 'FASW', 'FISH', 'FIRE', 'FITT', 'FLMC', 'FMII', 'FOOD',
    'FORU', 'FORZ', 'FPNI', 'FREN', 'FUTR', 'FUJI', 'GAMA', 'GDST', 'GDYR', 'GEMA',
    'GEMS', 'GGRP', 'GGRM', 'GIAA', 'GJTL', 'GLVA', 'GLOB', 'GMTD', 'GOLD', 'GOLL',
    'GOOD', 'GOLF', 'GPRA', 'GRIA', 'GSMF', 'GTSI', 'GTBO', 'GTRA', 'GULA',
    'GWSA', 'GZCO', 'HADE', 'HAJJ', 'HALO', 'HATM', 'HDFA', 'HDIT', 'HEAL', 'HELI',
    'HERO', 'HEXA', 'HGII', 'HILL', 'HITS', 'HKMU', 'HMSP', 'HOKI', 'HOME', 'HOMI',
    'HOTL', 'HOPE', 'HRME', 'HRUM', 'HUMI', 'IATA', 'IBFN', 'IBOS', 'IBST', 'ICBP',
    'ICON', 'ICOR', 'IDEA', 'IDPR', 'IFII', 'IFSH', 'IGAR', 'IIKP', 'IKAI', 'IKBI',
    'IKPM', 'IKAN', 'IMAS', 'IMJS', 'IMPC', 'INAF', 'INAI', 'INCI', 'INCF', 'INCO',
    'INDF', 'INDO', 'INDR', 'INDS', 'INDX', 'INDY', 'INET', 'INKP', 'INOC', 'INOV',
    'INPC', 'INPP', 'INPS', 'INRU', 'INTA', 'INTD', 'INTP', 'IPAC', 'IPCC', 'IPCM',
    'IPOL', 'IPPE', 'IPSA', 'IPTV', 'IRRA', 'ISAP', 'ISAT', 'ISEA', 'ISSP', 'ITIC',
    'ITMA', 'ITMG', 'IOTF', 'JARR', 'JAST', 'JATI', 'JAWA', 'JAYA', 'JECC', 'JGLE',
    'JIHD', 'JKON', 'JKSW', 'JMAS', 'JPFA', 'JRPT', 'JSMR', 'JSKY', 'JSPT',
    'JTPE', 'KAEF', 'KAYU', 'KBAG', 'KBLI', 'KBLM', 'KBLV', 'KBRI', 'KDSI', 'KEEN',
    'KEJU', 'KETR', 'KIAS', 'KICI', 'KING', 'KINO', 'KIJA', 'KKES', 'KKGI', 'KLAS',
    'KLBF', 'KLIN', 'KMDS', 'KMTR', 'KOBX', 'KOIN', 'KOKA', 'KONI', 'KOPI', 'KOTA',
    'KOCI', 'KPAL', 'KPIG', 'KRAH', 'KRAS', 'KREN', 'KRYA', 'KSIX', 'KUAS', 'LABA',
    'LABS', 'LAPD', 'LAJU', 'LAND', 'LCGP', 'LEAD', 'LIFE', 'LINK', 'LION', 'LIVE',
    'LMAS', 'LMPI', 'LMSH', 'LMAX', 'LPCK', 'LPGI', 'LPIN', 'LPKR', 'LPLI', 'LPPF',
    'LPPS', 'LRNA', 'LSIP', 'LTLS', 'LUCK', 'LUCY', 'MABA', 'MAGP', 'MAHA', 'MAIN',
    'MANG', 'MARI', 'MARK', 'MAMA', 'MAMI', 'MANA', 'MAPA', 'MAPB', 'MASA', 'MASB',
    'MAYA', 'MAXI', 'MBAP', 'MBMA', 'MBSS', 'MBTO', 'MCAS', 'MCOL', 'MCOR', 'MDIA',
    'MDIY', 'MDKA', 'MDKI', 'MDLN', 'MDRN', 'MEDC', 'MEDS', 'MEGA', 'MEJA', 'MENN',
    'MERA', 'MERK', 'META', 'MFIN', 'MFMI', 'MGNA', 'MGRO', 'MICE', 'MIDI', 'MIKA',
    'MINA', 'MIRA', 'MITI', 'MKAP', 'MKNT', 'MKPI', 'MKTR', 'MLBI', 'MLIA', 'MLPL',
    'MLPT', 'MMLP', 'MNCN', 'MORA', 'MPMX', 'MPXL', 'MPPA', 'MPRO', 'MRAT', 'MREI',
    'MSIN', 'MSIE', 'MSJA', 'MSKY', 'MSSL', 'MSTI', 'MTDL', 'MTFN', 'MTPS', 'MTLA',
    'MTSM', 'MTWI', 'MTRA', 'MUTU', 'MYOH', 'MYOR', 'MYRX', 'MYTX', 'NANO', 'NASI',
    'NATO', 'NASA', 'NAYZ', 'NCKL', 'NELY', 'NEST', 'NICL', 'NICK', 'NIKL', 'NINE',
    'NIRO', 'NIPS', 'NISP', 'NOBU', 'NRCA', 'NSSS', 'NUSA', 'NZIA', 'OBAT',
    'OBMD', 'OCAP', 'OKAS', 'OLIV', 'OMED', 'OMRE', 'OPMS', 'OILS', 'PACK', 'PADA',
    'PADI', 'PALM', 'PAMG', 'PANI', 'PANR', 'PANS', 'PART', 'PBID', 'PBRX', 'PBSA',
    'PEGE', 'PEHA', 'PEVE', 'PGAS', 'PGEO', 'PGLI', 'PGJO', 'PGUN', 'PICO', 'PIPA',
    'PJAA', 'PKPK', 'PLAN', 'PLAS', 'PLIN', 'PMJS', 'PMMP', 'PNGO', 'PNBN', 'PNBS',
    'PNIN', 'PNLF', 'PNSE', 'POLA', 'POLI', 'POLU', 'POOL', 'PORT', 'POSA', 'POWR',
    'PPGL', 'PPRE', 'PPRO', 'PRAS', 'PRAY', 'PRDA', 'PREM', 'PRIM', 'PSAB', 'PSDN',
    'PSGO', 'PSKT', 'PTBA', 'PTDU', 'PTIS', 'PTMP', 'PTMR', 'PTPP', 'PTPW', 'PTRO',
    'PTSN', 'PTSP', 'PUDP', 'PURA', 'PURE', 'PURI', 'PWON', 'PYFA', 'RAAM', 'RAJA',
    'RALS', 'RANC', 'RATU', 'RBMS', 'RCCC', 'RDTX', 'REAL', 'RELF', 'RELI', 'RGAS',
    'RGIO', 'RICY', 'RISE', 'RIGS', 'RIMO', 'RMKE', 'RMKO', 'ROCK', 'RODA', 'RONY',
    'ROTI', 'RSCH', 'RUIS', 'RUNS', 'SAFE', 'SAGE', 'SAME', 'SAMF', 'SAPX', 'SATU',
    'SBAT', 'SBMA', 'SCCO', 'SCMA', 'SCNP', 'SCPI', 'SDMU', 'SDPC', 'SDRA', 'SEMA',
    'SFAN', 'SGER', 'SGRO', 'SHID', 'SHIP', 'SIDO', 'SILO', 'SIMA', 'SIMP', 'SINI',
    'SICO', 'SKBM', 'SKLT', 'SKRN', 'SKYB', 'SLIS', 'SMAR', 'SMCB', 'SMCL', 'SMDM',
    'SMDR', 'SMGA', 'SMGR', 'SMIL', 'SMKL', 'SMMA', 'SMMT', 'SMRA', 'SMRU', 'SMSM',
    'SMKM', 'SMLE', 'SNLK', 'SOFA', 'SOHO', 'SOLA', 'SONA', 'SOSS', 'SOUL',
    'SPMA', 'SPRE', 'SQMI', 'SRAJ', 'SRIL', 'SRSN', 'SRTG', 'SSIA', 'SSMS', 'SSTM',
    'STAR', 'STAA', 'STTP', 'SUGI', 'SULI', 'SUNI', 'SUPR', 'SURE', 'SWAT', 'SWID',
    'TALF', 'TAMA', 'TAMU', 'TARA', 'TAXI', 'TBIG', 'TBLA', 'TBMS', 'TCID', 'TCPI',
    'TEBE', 'TECH', 'TELE', 'TFAS', 'TFCO', 'TGKA', 'TGUK', 'TIFA', 'TINS', 'TIRA',
    'TIRT', 'TKIM', 'TLKM', 'TMAS', 'TMPO', 'TOBA', 'TOOL', 'TOTO', 'TOTL', 'TOWR',
    'TOYS', 'TPMA', 'TPIA', 'TRAM', 'TRGU', 'TRIL', 'TRIM', 'TRIN', 'TRIO', 'TRIS',
    'TRJA', 'TRST', 'TRUK', 'TRUS', 'TRON', 'TSPC', 'TYRE', 'UANG', 'UCID',
    'UDNG', 'ULTJ', 'UNIC', 'UNIT', 'UNIQ', 'UNSP', 'UNTD', 'UNTR', 'UNVR', 'URBN',
    'UVCR', 'VAST', 'VICI', 'VICO', 'VINS', 'VIVA', 'VKTR', 'VOKS', 'VRNA', 'VTNY',
    'WAPO', 'WEGE', 'WEHA', 'WIDI', 'WIFI', 'WINE', 'WINS', 'WIRG', 'WIIM', 'WIKA',
    'WOMF', 'WOOD', 'WOWS', 'WSBP', 'WSKT', 'WTON', 'WGSH', 'YULE', 'YPAS',
    'ZATA', 'ZBRA', 'ZINC', 'ZONE', 'ZYRX',
]

IDX_TICKERS_COMPLETE = sorted(list(set([t.upper() for t in IDX_TICKERS_COMPLETE if t.strip()])))

if __name__ == '__main__':
    print(f"📊 Total {len(IDX_TICKERS_COMPLETE)} ticker IDX terdaftar")
    print(f"📅 Data sumber: IDX Official")
    print(f"\nContoh 20 ticker pertama:")
    for i, ticker in enumerate(IDX_TICKERS_COMPLETE[:20], 1):
        print(f"  {i:3d}. {ticker}")
